package app.usecases;

public enum UseCaseId {
    ECOM_CREAR_PEDIDO,
    ECOM_AGREGAR_PRODUCTOS,
    ECOM_PAGAR_PEDIDO,
    ECOM_AVANZAR_ESTADO,
    DEMO_DIAMANTE_PAGOS,
    ECOM_VER_RESUMEN,
    EXCEP_DIVISION_SEGURA,
    EXCEP_TEXTO_A_NUMERO,
    EXCEP_LECTURA_ARCHIVO,
    EXCEP_PERSONALIZADA,
    EXCEP_TRY_WITH_RESOURCES
}
